name: Linux (Ubuntu-24.04) CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - { compiler: gcc, version: 14, std: 23, build_type: Release }
          #- { compiler: clang, version: 20, std: 23, build_type: Release }
    name: "${{matrix.config.compiler}} ${{matrix.config.version}} (C++${{matrix.config.std}}, ${{matrix.config.build_type}})"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.config.compiler }}-${{ matrix.config.version }}
          ninja: true

      - name: Install system packages
        run: |
          apt-get update && \
          apt-get install -y libgrpc++-dev libgrpc-dev

      - name: Install Dependencies
        run: |
          git clone --branch 2025.10.17 --depth 1 https://github.com/microsoft/vcpkg.git && \
          cd vcpkg && \
          ./bootstrap-vcpkg.sh && \
          ./vcpkg install

      - name: Configure
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=scripts/buildsystems/vcpkg.cmake \
                   -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
                   -DCMAKE_CXX_STANDARD=${{ matrix.config.std }}

      - name: Build
        run: |
          cmake --build rediska -j $(nproc)

      - name: Test
        run: |
          ctest --exclude-regex static --test-dir build -j $(nproc) --output-on-failure
